
deployment:
  replicaCount: 1
  autoscaling:
    enabled: true
    replicas:
      min: 2
      max: 10
  volumeMounts:
    - name: datakeys
      mountPath: /mnt/keys
    - name: accesstoken
      mountPath: "/accesstoken"

  volumes:
    - name : datakeys
      persistentVolumeClaim:
        claimName: keys
    - name: accesstoken
      secret:
        secretName: accesstoken

  readiness:
    enabled: true

  liveness:
    enabled: true
